// KOMENTARZ (Dlaczego?):
// Poprawiamy dwie rzeczy:
// 1. Dodajemy brakujący znak "=" po nazwie zmiennej.
// 2. Zmieniamy nazwę z "IMIENINY_BAZA" na "imieninyData",
//    ponieważ tej nazwy szuka funkcja getImieniny() w pliku index.html.
const imieninyData = {
    'styczeń': {
        '1': ['Mieszka', 'Mieczysława', 'Marii'], '2': ['Bazylego', 'Grzegorza', 'Makarego'],
        '3': ['Danuty', 'Daniela', 'Genowefy'], '4': ['Elżbiety', 'Anieli', 'Eugeniusza'],
        '5': ['Hanny', 'Edwarda', 'Szymona'], '6': ['Kacpra', 'Melchiora', 'Baltazara'],
        '7': ['Lucjana', 'Juliana', 'Rajmunda'], '8': ['Seweryna', 'Mścisława', 'Juliusza'],
        '9': ['Adrianny', 'Juliana', 'Piotra'], '10': ['Wilhelma', 'Agatona', 'Danuty'],
        '11': ['Feliksa', 'Honoraty', 'Matyldy'], '12': ['Grety', 'Arkadiusza', 'Benedykta'],
        '13': ['Weroniki', 'Bogumiła', 'Godfryda'], '14': ['Feliksa', 'Hilarego', 'Niny'],
        '15': ['Pawła', 'Arnolda', 'Izydora'], '16': ['Marcelego', 'Włodzimierza', 'Waldemara'],
        '17': ['Antoniego', 'Rościsława', 'Jana'], '18': ['Małgorzaty', 'Piotra', 'Sędziwoja'],
        '19': ['Henryka', 'Mariusza', 'Marty'], '20': ['Fabiana', 'Sebastiana', 'Dobromiły'],
        '21': ['Agnieszki', 'Jarosława', 'Inez'], '22': ['Wincentego', 'Anastazego', 'Władysława'],
        '23': ['Ildefonsa', 'Rajmunda', 'Zenona'], '24': ['Felicji', 'Franciszka', 'Rafała'],
        '25': ['Pawła', 'Miłosza', 'Tatiany'], '26': ['Tymoteusza', 'Tytusa', 'Pauliny'],
        '27': ['Anieli', 'Jerzego', 'Ilony'], '28': ['Tomasza', 'Waleriusza', 'Karola'],
        '29': ['Franciszka', 'Zdzisława', 'Józefa'], '30': ['Macieja', 'Martyny', 'Gerarda'],
        '31': ['Jana', 'Marceli', 'Ludwiki']
    },
    'luty': {
        '1': ['Brygidy', 'Ignacego', 'Dobromiry'], '2': ['Marii', 'Mileny', 'Mirosława'],
        '3': ['Błażeja', 'Oskara', 'Joanny'], '4': ['Weroniki', 'Andrzeja', 'Józefa'],
        '5': ['Agaty', 'Adelajdy', 'Filipa'], '6': ['Doroty', 'Tytusa', 'Bogdana'],
        '7': ['Ryszarda', 'Romualda', 'Teodora'], '8': ['Hieronima', 'Jana', 'Piotra'],
        '9': ['Cyryla', 'Apolonii', 'Rajnolda'], '10': ['Elwiry', 'Jacka', 'Scholastyki'],
        '11': ['Lucjana', 'Olgierda', 'Marii'], '12': ['Eulalii', 'Radosława', 'Modesta'],
        '13': ['Grzegorza', 'Katarzyny', 'Lesława'], '14': ['Walentego', 'Cyryla', 'Metodego'],
        '15': ['Jowity', 'Faustyna', 'Zygfryda'], '16': ['Danuty', 'Juliany', 'Daniela'],
        '17': ['Aleksandra', 'Łukasza', 'Zbigniewa'], '18': ['Szymona', 'Konstancji', 'Flawiana'],
        '19': ['Arnolda', 'Konrada', 'Józefa'], '20': ['Leona', 'Ludomira', 'Zenobiusza'],
        '21': ['Eleonory', 'Feliksa', 'Piotra'], '22': ['Małgorzaty', 'Marty', 'Piotra'],
        '23': ['Romany', 'Damiana', 'Polikarpa'], '24': ['Macieja', 'Bogusza', 'Sergiusza'],
        '25': ['Wiktora', 'Cezarego', 'Ewalda'], '26': ['Mirosława', 'Aleksandra', 'Dionizego'],
        '27': ['Gabriela', 'Anastazji', 'Juliana'], '28': ['Romana', 'Ludomira', 'Makarego'],
        '29': ['Lecha', 'Lutomira'] // (tylko w lata przestępne)
    },
    'marzec': {
        '1': ['Antoniny', 'Radosława', 'Dawida'], '2': ['Heleny', 'Halszki', 'Pawła'],
        '3': ['Kingi', 'Tycjana', 'Kunegundy'], '4': ['Kazimierza', 'Lucji', 'Eugeniusza'],
        '5': ['Adriana', 'Fryderyka', 'Teofila'], '6': ['Róży', 'Wiktora', 'Jordana'],
        '7': ['Pawła', 'Tomasza', 'Perpetuy'], '8': ['Beaty', 'Wincentego', 'Jana'],
        '9': ['Franciszki', 'Dominika', 'Katarzyny'], '10': ['Cypriana', 'Marcelego', 'Aleksandra'],
        '11': ['Konstantego', 'Ludwika', 'Benedykta'], '12': ['Grzegorza', 'Justyna', 'Bernarda'],
        '13': ['Bożeny', 'Krystyny', 'Marka'], '14': ['Leona', 'Matyldy', 'Łazarza'],
        '15': ['Klemensa', 'Longina', 'Ludwiki'], '16': ['Izabeli', 'Hilarego', 'Oktawiana'],
        '17': ['Patryka', 'Zbigniewa', 'Gertrudy'], '18': ['Cyryla', 'Edwarda', 'Aleksandra'],
        '19': ['Józefa', 'Bogdana', 'Leoncjusza'], '20': ['Joachima', 'Klaudii', 'Eufemii'],
        '21': ['Benedykta', 'Lubomira', 'Marzanny'], '22': ['Bogusława', 'Katarzyny', 'Kazimierza'],
        '23': ['Pelagii', 'Oktawiana', 'Feliksa'], '24': ['Marka', 'Gabriela', 'Seweryna'],
        '25': ['Marii', 'Wieńczysława', 'Ireneusza'], '26': ['Larysy', 'Emanuela', 'Teodora'],
        '27': ['Lidii', 'Ernesta', 'Jana'], '28': ['Anieli', 'Sykstusa', 'Jana'],
        '29': ['Wiktoryna', 'Helmuta', 'Eustachego'], '30': ['Amelii', 'Leonarda', 'Kwiryna'],
        '31': ['Beniamina', 'Balbiny', 'Gwidona']
    },
    'kwiecień': {
        '1': ['Grażyny', 'Hugona', 'Zbigniewa'], '2': ['Władysława', 'Franciszka', 'Teodozji'],
        '3': ['Ryszarda', 'Pankracego', 'Ingi'], '4': ['Izydora', 'Wacława', 'Benedykta'],
        '5': ['Ireny', 'Wincentego', 'Justyna'], '6': ['Celestyna', 'Wilhelma', 'Sixtusa'],
        '7': ['Donata', 'Hermana', 'Rufina'], '8': ['Dionizego', 'Julii', 'Radosława'],
        '9': ['Marcelego', 'Marii', 'Heliodora'], '10': ['Michała', 'Makarego', 'Danieli'],
        '11': ['Gemy', 'Leona', 'Filipa'], '12': ['Juliusza', 'Wiktora', 'Zenona'],
        '13': ['Przemysława', 'Hermenegildy', 'Marcina'], '14': ['Bernarda', 'Justyny', 'Waleriana'],
        '15': ['Anastazji', 'Ludwiny', 'Wacławy'], '16': ['Julii', 'Bernadety', 'Benedykta'],
        '17': ['Roberta', 'Klary', 'Aniceta'], '18': ['Bogusławy', 'Gościmira', 'Apoloniusza'],
        '19': ['Adolfa', 'Leona', 'Tymona'], '20': ['Czesława', 'Agnieszki', 'Teodora'],
        '21': ['Anzelma', 'Feliksa', 'Konrada'], '22': ['Kazimierza', 'Łukasza', 'Leonii'],
        '23': ['Jerzego', 'Wojciecha', 'Adalberta'], '24': ['Grzegorza', 'Horacego', 'Aleksego'],
        '25': ['Marka', 'Jarosława', 'Wioletty'], '26': ['Marzeny', 'Klaudiusza', 'Marii'],
        '27': ['Zyty', 'Anastazego', 'Teofila'], '28': ['Pawła', 'Walerii', 'Piotra'],
        '29': ['Piotra', 'Rity', 'Hugona'], '30': ['Mariana', 'Katarzyny', 'Jakuba']
    },
    'maj': {
        '1': ['Józefa', 'Jeremiasza', 'Lubomira'], '2': ['Zygmunta', 'Anatola', 'Walentego'],
        '3': ['Marii', 'Antoniny', 'Aleksandra'], '4': ['Floriana', 'Moniki', 'Paulina'],
        '5': ['Ireny', 'Waldemara', 'Grzegorza'], '6': ['Jana', 'Judyty', 'Filipa'],
        '7': ['Gizeli', 'Ludomira', 'Benedykta'], '8': ['Stanisława', 'Lizy', 'Dezyderii'],
        '9': ['Grzegorza', 'Karoliny', 'Bożydara'], '10': ['Antoniego', 'Izydora', 'Wiktoryny'],
        '11': ['Franciszka', 'Ignacego', 'Miry'], '12': ['Pankracego', 'Dominika', 'Joanny'],
        '13': ['Serwacego', 'Roberta', 'Glorii'], '14': ['Bonifacego', 'Macieja', 'Dobiesława'],
        '15': ['Zofii', 'Izydora', 'Jana'], '16': ['Andrzeja', 'Szymona', 'Jędrzeja'],
        '17': ['Paschalisa', 'Brunona', 'Sławomira'], '18': ['Eryka', 'Feliksa', 'Jana'],
        '19': ['Piotra', 'Iwa', 'Mikołaja'], '20': ['Bernarda', 'Aleksandra', 'Bazylego'],
        '21': ['Wiktora', 'Tymoteusza', 'Jana'], '22': ['Rity', 'Julii', 'Heleny'],
        '23': ['Iwony', 'Dezyderego', 'Emilii'], '24': ['Joanny', 'Zuzanny', 'Jana'],
        '25': ['Grzegorza', 'Urbana', 'Magdaleny'], '26': ['Filipa', 'Pauliny', 'Eweliny'],
        '27': ['Augustyna', 'Jana', 'Juliusza'], '28': ['Jaromira', 'Justa', 'Wilhelma'],
        '29': ['Magdaleny', 'Teodozji', 'Maksymina'], '30': ['Feliksa', 'Joanny', 'Ferdynanda'],
        '31': ['Anieli', 'Kamili', 'Petroneli']
    },
    'czerwiec': {
        '1': ['Jakuba', 'Konrada', 'Justyna'], '2': ['Marii', 'Erazma', 'Eugeniusza'],
        '3': ['Leszka', 'Kłotyldy', 'Owidiusza'], '4': ['Karola', 'Franciszka', 'Helgi'],
        '5': ['Bonifacego', 'Waltera', 'Kiry'], '6': ['Norberta', 'Laurentego', 'Pauliny'],
        '7': ['Roberta', 'Wiesławy', 'Antoniego'], '8': ['Medarda', 'Maksyma', 'Seweryna'],
        '9': ['Pelagii', 'Felicjana', 'Anny'], '10': ['Bogumiła', 'Małgorzaty', 'Diany'],
        '11': ['Barnaby', 'Benedykta', 'Feliksa'], '12': ['Jana', 'Onufrego', 'Mieczysławy'],
        '13': ['Antoniego', 'Lucyny', 'Gerarda'], '14': ['Bazylego', 'Elizy', 'Justyna'],
        '15': ['Wita', 'Jolanty', 'Modesta'], '16': ['Aliny', 'Justyny', 'Benona'],
        '17': ['Laury', 'Alberta', 'Adolfa'], '18': ['Marka', 'Elżbiety', 'Pauliny'],
        '19': ['Gerwazego', 'Protazego', 'Romualda'], '20': ['Bogny', 'Florentyny', 'Rafała'],
        '21': ['Alicji', 'Alojzego', 'Rudolfa'], '22': ['Pauliny', 'Tomasza', 'Jana'],
        '23': ['Wandy', 'Zenona', 'Albiny'], '24': ['Jana', 'Danuty', 'Emilii'],
        '25': ['Łucji', 'Wilhelma', 'Doroty'], '26': ['Jana', 'Pawła', 'Tytusa'],
        '27': ['Marii', 'Władysława', 'Cyryla'], '28': ['Leona', 'Ireneusza', 'Flory'],
        '29': ['Piotra', 'Pawła', 'Władysławy'], '30': ['Emilii', 'Lucyny', 'Arnolda']
    },
    'lipiec': {
        '1': ['Haliny', 'Mariana', 'Bogusza'], '2': ['Marii', 'Urbana', 'Jagody'],
        '3': ['Jacka', 'Anatola', 'Tomasza'], '4': ['Elżbiety', 'Eugeniusza', 'Malwiny'],
        '5': ['Antoniego', 'Karoliny', 'Bartłomieja'], '6': ['Dominiki', 'Łucji', 'Gotfryda'],
        '7': ['Cyryla', 'Metodego', 'Rudolfa'], '8': ['Edgara', 'Elżbiety', 'Eugeniusza'],
        '9': ['Weroniki', 'Zenona', 'Sylwii'], '10': ['Filipa', 'Amelii', 'Witalisa'],
        '11': ['Benedykta', 'Olgi', 'Kaliny'], '12': ['Jana', 'Brunona', 'Weroniki'],
        '13': ['Małgorzaty', 'Henryka', 'Sary'], '14': ['Kamila', 'Izabeli', 'Marceliny'],
        '15': ['Henryka', 'Włodzimierza', 'Bonawentury'], '16': ['Marii', 'Mariki', 'Benedykta'],
        '17': ['Aleksego', 'Anety', 'Bogdana'], '18': ['Kamila', 'Szymona', 'Emilii'],
        '19': ['Wincentego', 'Wodzisława', 'Marcina'], '20': ['Czesława', 'Małgorzaty', 'Hieronima'],
        '21': ['Daniela', 'Wiktora', 'Andrzeja'], '22': ['Marii Magdaleny', 'Bolesława', 'Mileny'],
        '23': ['Brygidy', 'Apolinarego', 'Bogny'], '24': ['Kingi', 'Krystyny', 'Jakuba'],
        '25': ['Krzysztofa', 'Jakuba', 'Walentyny'], '26': ['Anny', 'Joachima', 'Hanny'],
        '27': ['Julii', 'Natalii', 'Rudolfa'], '28': ['Wiktora', 'Innocentego', 'Ady'],
        '29': ['Marty', 'Ludwika', 'Olafa'], '30': ['Julity', 'Piotra', 'Ludomira'],
        '31': ['Ignacego', 'Heleny', 'Ludomira']
    },
    'sierpień': {
        '1': ['Alfonsa', 'Justyna', 'Piotra'], '2': ['Kariny', 'Gustawa', 'Euzebiusza'],
        '3': ['Lidii', 'Augusta', 'Nikodema'], '4': ['Dominika', 'Protazego', 'Jana'],
        '5': ['Marii', 'Oswalda', 'Abel'], '6': ['Sławy', 'Jakuba', 'Wincentego'],
        '7': ['Klaudii', 'Donaty', 'Kajetana'], '8': ['Emiliana', 'Dominika', 'Cypriana'],
        '9': ['Romana', 'Ryszarda', 'Edyty'], '10': ['Wawrzyńca', 'Bogdana', 'Borysa'],
        '11': ['Klary', 'Zuzanny', 'Lecha'], '12': ['Lecha', 'Hilarii', 'Juliana'],
        '13': ['Hipolita', 'Poncjana', 'Diany'], '14': ['Maksymiliana', 'Alfreda', 'Euzebiusza'],
        '15': ['Marii', 'Napoleona', 'Stelii'], '16': ['Rocha', 'Stefana', 'Joachima'],
        '17': ['Jacka', 'Anity', 'Joanny'], '18': ['Ilony', 'Heleny', 'Klary'],
        '19': ['Bolesława', 'Juliana', 'Jana'], '20': ['Bernarda', 'Samuela', 'Sabiny'],
        '21': ['Franciszka', 'Joanny', 'Piusa'], '22': ['Marii', 'Cezarego', 'Tymoteusza'],
        '23': ['Filipa', 'Apolinarego', 'Róży'], '24': ['Bartłomieja', 'Jerzego', 'Emilii'],
        '25': ['Ludwika', 'Luizy', 'Józefa'], '26': ['Marii', 'Zefiryny', 'Aleksandra'],
        '27': ['Moniki', 'Cezarego', 'Józefa'], '28': ['Augustyna', 'Patrycji', 'Erazma'],
        '29': ['Jana', 'Sabiny', 'Racibora'], '30': ['Róży', 'Feliksa', 'Szczęsnego'],
        '31': ['Rajmunda', 'Bohdana', 'Pauliny']
    },
    'wrzesień': {
        '1': ['Idziego', 'Bronisława', 'Egidiusza'], '2': ['Stefana', 'Wilhelma', 'Juliana'],
        '3': ['Izabeli', 'Grzegorza', 'Szymona'], '4': ['Rozalii', 'Róży', 'Idy'],
        '5': ['Laury', 'Wawrzyńca', 'Justyna'], '6': ['Beaty', 'Eugeniusza', 'Zachariasza'],
        '7': ['Reginy', 'Marka', 'Melchiora'], '8': ['Marii', 'Adrianny', 'Klementyny'],
        '9': ['Piotra', 'Sergiusza', 'Aldony'], '10': ['Mikołaja', 'Łukasza', 'Klemensa'],
        '11': ['Jacka', 'Hiacynty', 'Dagny'], '12': ['Marii', 'Gwidona', 'Radzimira'],
        '13': ['Jana', 'Eugenii', 'Aureliusza'], '14': ['Bernarda', 'Roksany', 'Cypriana'],
        '15': ['Marii', 'Nikodema', 'Albina'], '16': ['Kornela', 'Cypriana', 'Edyty'],
        '17': ['Roberta', 'Hildegardy', 'Justyna'], '18': ['Józefa', 'Stanisława', 'Ireny'],
        '19': ['Konstancji', 'Januarii', 'Teodora'], '20': ['Eustachego', 'Faustyny', 'Ewy'],
        '21': ['Mateusza', 'Jonasza', 'Hipolita'], '22': ['Tomasza', 'Maurycego', 'Joachima'],
        '23': ['Tekli', 'Bogusława', 'Linusa'], '24': ['Gerarda', 'Teodora', 'Marii'],
        '25': ['Aurelii', 'Kleofasa', 'Władysława'], '26': ['Cypriana', 'Justyny', 'Damiana'],
        '27': ['Wincentego', 'Kosmy', 'Mirabeli'], '28': ['Wacława', 'Marka', 'Leonarda'],
        '29': ['Michała', 'Michaliny', 'Rafała'], '30': ['Hieronima', 'Zofii', 'Honoriusza']
    },
    'październik': {
        '1': ['Remigiusza', 'Teresy', 'Danuty'], '2': ['Teofila', 'Sławy', 'Dionizego'],
        '3': ['Gerarda', 'Teresy', 'Heliodora'], '4': ['Franciszka', 'Rozalii', 'Edwina'],
        '5': ['Placyda', 'Faustyny', 'Rajmunda'], '6': ['Brunona', 'Artura', 'Fryderyki'],
        '7': ['Marii', 'Marka', 'Justyny'], '8': ['Pelagii', 'Brygidy', 'Walerii'],
        '9': ['Dionizego', 'Arnolda', 'Ludwika'], '10': ['Franciszka', 'Pauliny', 'Danieli'],
        '11': ['Emila', 'Marii', 'Aldony'], '12': ['Maksymiliana', 'Eustachego', 'Krystyny'],
        '13': ['Edwarda', 'Teofila', 'Bernarda'], '14': ['Bernarda', 'Damiana', 'Kaliksta'],
        '15': ['Teresy', 'Jadwigi', 'Leonarda'], '16': ['Gawła', 'Jadwigi', 'Florentyny'],
        '17': ['Ignacego', 'Wiktora', 'Małgorzaty'], '18': ['Łukasza', 'Juliana', 'Hanny'],
        '19': ['Piotra', 'Pawła', 'Ziemowita'], '20': ['Ireny', 'Jana', 'Witalisa'],
        '21': ['Urszuli', 'Hilarego', 'Jakuba'], '22': ['Filipa', 'Korduli', 'Lody'],
        '23': ['Seweryna', 'Teodora', 'Jana'], '24': ['Rafała', 'Marcina', 'Antoniego'],
        '25': ['Darii', 'Ingi', 'Maurycego'], '26': ['Lucjana', 'Ewy', 'Damiana'],
        '27': ['Wincentego', 'Iwony', 'Sabiny'], '28': ['Szymona', 'Judy', 'Tadeusza'],
        '29': ['Wioletty', 'Euzebii', 'Zenobii'], '30': ['Przemysława', 'Edmunda', 'Alfonsa'],
        '31': ['Augusta', 'Lucjana', 'Urbana']
    },
    'listopad': {
        '1': ['Wszystkich Świętych'], '2': ['Bohdany', 'Dzień Zaduszny'],
        '3': ['Sylwii', 'Huberta', 'Marcina'], '4': ['Karola', 'Olgierda', 'Emeryka'],
        '5': ['Elżbiety', 'Sławomira', 'Dominika'], '6': ['Feliksa', 'Leonarda', 'Ziemowita'],
        '7': ['Ernesta', 'Antoniego', 'Bogumiła'], '8': ['Seweryna', 'Klaudiusza', 'Wiktora'],
        '9': ['Teodora', 'Ursyna', 'Genowefy'], '10': ['Leona', 'Ludomira', 'Natalii'],
        '11': ['Marcina', 'Bartłomieja', 'Teodora'], '12': ['Renaty', 'Witolda', 'Konrada'],
        '13': ['Stanisława', 'Mikołaja', 'Liwii'], '14': ['Wawrzyńca', 'Emila', 'Rogera'],
        '15': ['Alberta', 'Leopolda', 'Idalii'], '16': ['Marka', 'Gertrudy', 'Edmunda'],
        '17': ['Grzegorza', 'Salomei', 'Elżbiety'], '18': ['Romana', 'Tomasza', 'Karoliny'],
        '19': ['Elżbiety', 'Seweryna', 'Matyldy'], '20': ['Feliksa', 'Anatola', 'Rafała'],
        '21': ['Konrada', 'Janusza', 'Marii'], '22': ['Cecylii', 'Marka', 'Wszemiły'],
        '23': ['Klemensa', 'Felicyty', 'Adeli'], '24': ['Flory', 'Emmy', 'Franciszka'],
        '25': ['Katarzyny', 'Erazma', 'Tęgomira'], '26': ['Konrada', 'Sylwestra', 'Leonarda'],
        '27': ['Waleriana', 'Wirgiliusza', 'Maksymiliana'], '28': ['Zdzisława', 'Jakuba', 'Stefana'],
        '29': ['Błażeja', 'Saturnina', 'Maury'], '30': ['Andrzeja', 'Maury', 'Konstantego']
    },
    'grudzień': {
        '1': ['Natalii', 'Eligiusza', 'Edmunda'], '2': ['Balbiny', 'Pauliny', 'Ksawerego'],
        '3': ['Franciszka', 'Ksawerego', 'Kasjana'], '4': ['Barbary', 'Krystiana', 'Hieronima'],
        '5': ['Sabiny', 'Kryspiny', 'Gerarda'], '6': ['Mikołaja', 'Angeliki', 'Emila'],
        '7': ['Ambrożego', 'Marcina', 'Teodora'], '8': ['Marii', 'Światozara', 'Klemensa'],
        '9': ['Wiesławy', 'Leokadii', 'Joanny'], '10': ['Julii', 'Danieli', 'Grzegorza'],
        '11': ['Damazego', 'Waldemara', 'Daniela'], '12': ['Aleksandra', 'Dagmary', 'Adama'],
        '13': ['Łucji', 'Otylii', 'Zorzy'], '14': ['Alfreda', 'Izydora', 'Jana'],
        '15': ['Celiny', 'Waleriana', 'Niny'], '16': ['Euzebiusza', 'Albiny', 'Zdzisławy'],
        '17': ['Łazarza', 'Floriana', 'Olimpii'], '18': ['Gracjana', 'Bogusława', 'Laurentego'],
        '19': ['Gabrieli', 'Dariusza', 'Eleonory'], '20': ['Dominika', 'Bogumiły', 'Teofila'],
        '21': ['Tomasza', 'Piotra', 'Honoraty'], '22': ['Zenona', 'Honoraty', 'Beaty'],
        '23': ['Wiktorii', 'Sławomiry', 'Jana'], '24': ['Adama', 'Ewy', 'Eweliny'],
        '25': ['Anastazji', 'Eugenii', 'Piotra'], '26': ['Szczepana', 'Dionizego', 'Wróciwoja'],
        '27': ['Jana', 'Żanety', 'Fabioli'], '28': ['Teofilii', 'Antoniusza', 'Cezarego'],
        '29': ['Tomasza', 'Dawida', 'Dominika'], '30': ['Eugeniusza', 'Katarzyny', 'Sabiny'],
        '31': ['Sylwestra', 'Melanii', 'Mariusza']
    }
};
