/**
 * @file imieniny.js
 * @description Plik ten zawiera stałą bazę danych imienin w Polsce.
 * Jest ona zorganizowana jako obiekt (słownik), gdzie klucze reprezentują
 * konkretne dni w roku, a wartości to lista imion obchodzących tego dnia imieniny.
 */

// Definicja stałej `IMIENINY_BAZA` (IMIENINY_BAZA).
// Używamy `const`, ponieważ ta baza danych nie powinna być modyfikowana
// w trakcie działania programu (jest to statyczny zbiór danych).
const IMIENINY_BAZA = {
    // Struktura danych:
    // Klucz: 'MM-DD' (Miesiąc-Dzień) - reprezentuje datę w sposób
    // łatwy do sortowania i odpytywania.
    // Wartość: 'Imię1, Imię2, Imię3' - ciąg znaków (string)
    // zawierający imiona oddzielone przecinkami i spacją.

    // --- Styczeń ---
    '01-01': 'Mieszka, Mieczysława, Marii',
    '01-02': 'Bazylego, Grzegorza, Makarego',
    '01-03': 'Danuty, Daniela, Genowefy',
    '01-04': 'Elżbiety, Anieli, Eugeniusza',
    '01-05': 'Hanny, Edwarda, Szymona',
    '01-06': 'Kacpra, Melchiora, Baltazara', // Trzech Króli
    '01-07': 'Lucjana, Juliana, Rajmunda',
    '01-08': 'Seweryna, Mścisława, Juliusza',
    '01-09': 'Adrianny, Juliana, Piotra',
    '01-10': 'Wilhelma, Agatona, Danuty',
    '01-11': 'Feliksa, Honoraty, Matyldy',
    '01-12': 'Grety, Arkadiusza, Benedykta',
    '01-13': 'Weroniki, Bogumiła, Godfryda',
    '01-14': 'Feliksa, Hilarego, Niny',
    '01-15': 'Pawła, Arnolda, Izydora',
    '01-16': 'Marcelego, Włodzimierza, Waldemara',
    '01-17': 'Antoniego, Rościsława, Jana',
    '01-18': 'Małgorzaty, Piotra, Sędziwoja',
    '01-19': 'Henryka, Mariusza, Marty',
    '01-20': 'Fabiana, Sebastiana, Dobromiły',
    '01-21': 'Agnieszki, Jarosława, Inez',
    '01-22': 'Wincentego, Anastazego, Władysława',
    '01-23': 'Ildefonsa, Rajmunda, Zenona',
    '01-24': 'Felicji, Franciszka, Rafała',
    '01-25': 'Pawła, Miłosza, Tatiany',
    '01-26': 'Tymoteusza, Tytusa, Pauliny',
    '01-27': 'Anieli, Jerzego, Ilony',
    '01-28': 'Tomasza, Waleriusza, Karola',
    '01-29': 'Franciszka, Zdzisława, Józefa',
    '01-30': 'Macieja, Martyny, Gerarda',
    '01-31': 'Jana, Marceli, Ludwiki',

    // --- Luty ---
    '02-01': 'Brygidy, Ignacego, Dobromiry',
    '02-02': 'Marii, Mileny, Mirosława',
    '02-03': 'Błażeja, Oskara, Joanny',
    '02-04': 'Weroniki, Andrzeja, Józefa',
    '02-05': 'Agaty, Adelajdy, Filipa',
    '02-06': 'Doroty, Tytusa, Bogdana',
    '02-07': 'Ryszarda, Romualda, Teodora',
    '02-08': 'Hieronima, Jana, Piotra',
    '02-09': 'Cyryla, Apolonii, Rajnolda',
    '02-10': 'Elwiry, Jacka, Scholastyki',
    '02-11': 'Lucjana, Olgierda, Marii',
    '02-12': 'Eulalii, Radosława, Modesta',
    '02-13': 'Grzegorza, Katarzyny, Lesława',
    '02-14': 'Walentego, Cyryla, Metodego', // Walentynki
    '02-15': 'Jowity, Faustyna, Zygfryda',
    '02-16': 'Danuty, Juliany, Daniela',
    '02-17': 'Aleksandra, Łukasza, Zbigniewa',
    '02-18': 'Szymona, Konstancji, Flawiana',
    '02-19': 'Arnolda, Konrada, Józefa',
    '02-20': 'Leona, Ludomira, Zenobiusza',
    '02-21': 'Eleonory, Feliksa, Piotra',
    '02-22': 'Małgorzaty, Marty, Piotra',
    '02-23': 'Romany, Damiana, Polikarpa',
    '02-24': 'Macieja, Bogusza, Sergiusza',
    '02-25': 'Wiktora, Cezarego, Ewalda',
    '02-26': 'Mirosława, Aleksandra, Dionizego',
    '02-27': 'Gabriela, Anastazji, Juliana',
    '02-28': 'Romana, Ludomira, Makarego',
    // Specjalny przypadek dla roku przestępnego.
    // Logika aplikacji korzystająca z tej bazy musi obsłużyć
    // sprawdzanie, czy dany rok jest przestępny, aby poprawnie
    // zinterpretować ten wpis.
    '02-29': 'Lecha, Lutomira (tylko w lata przestępne)',

    // --- Marzec ---
    '03-01': 'Antoniny, Radosława, Dawida',
    '03-02': 'Heleny, Halszki, Pawła',
    '03-03': 'Kingi, Tycjana, Kunegundy',
    '03-04': 'Kazimierza, Lucji, Eugeniusza',
    '03-05': 'Adriana, Fryderyka, Teofila',
    '03-06': 'Róży, Wiktora, Jordana',
    '03-07': 'Pawła, Tomasza, Perpetuy',
    '03-08': 'Beaty, Wincentego, Jana', // Dzień Kobiet
    '03-09': 'Franciszki, Dominika, Katarzyny',
    '03-10': 'Cypriana, Marcelego, Aleksandra',
    '03-11': 'Konstantego, Ludwika, Benedykta',
    '03-12': 'Grzegorza, Justyna, Bernarda',
    '03-13': 'Bożeny, Krystyny, Marka',
    '03-14': 'Leona, Matyldy, Łazarza',
    '03-15': 'Klemensa, Longina, Ludwiki',
    '03-16': 'Izabeli, Hilarego, Oktawiana',
    '03-17': 'Patryka, Zbigniewa, Gertrudy',
    '03-18': 'Cyryla, Edwarda, Aleksandra',
    '03-19': 'Józefa, Bogdana, Leoncjusza',
    '03-20': 'Joachima, Klaudii, Eufemii',
    '03-21': 'Benedykta, Lubomira, Marzanny',
    '03-22': 'Bogusława, Katarzyny, Kazimierza',
    '03-23': 'Pelagii, Oktawiana, Feliksa',
    '03-24': 'Marka, Gabriela, Seweryna',
    '03-25': 'Marii, Wieńczysława, Ireneusza',
    '03-26': 'Larysy, Emanuela, Teodora',
    '03-27': 'Lidii, Ernesta, Jana',
    '03-28': 'Anieli, Sykstusa, Jana',
    '03-29': 'Wiktoryna, Helmuta, Eustachego',
    '03-30': 'Amelii, Leonarda, Kwiryna',
    '03-31': 'Beniamina, Balbiny, Gwidona',

    // --- Kwiecień ---
    '04-01': 'Grażyny, Hugona, Zbigniewa', // Prima Aprilis
    '04-02': 'Władysława, Franciszka, Teodozji',
    '04-03': 'Ryszarda, Pankracego, Ingi',
    '04-04': 'Izydora, Wacława, Benedykta',
    '04-05': 'Ireny, Wincentego, Justyna',
    '04-06': 'Celestyna, Wilhelma, Sixtusa',
    '04-07': 'Donata, Hermana, Rufina',
    '04-08': 'Dionizego, Julii, Radosława',
    '04-09': 'Marcelego, Marii, Heliodora',
    '04-10': 'Michała, Makarego, Danieli',
    '04-11': 'Gemy, Leona, Filipa',
    '04-12': 'Juliusza, Wiktora, Zenona',
    '04-13': 'Przemysława, Hermenegildy, Marcina',
    '04-14': 'Bernarda, Justyny, Waleriana',
    '04-15': 'Anastazji, Ludwiny, Wacławy',
    '04-16': 'Julii, Bernadety, Benedykta',
    '04-17': 'Roberta, Klary, Aniceta',
    '04-18': 'Bogusławy, Gościmira, Apoloniusza',
    '04-19': 'Adolfa, Leona, Tymona',
    '04-20': 'Czesława, Agnieszki, Teodora',
    '04-21': 'Anzelma, Feliksa, Konrada',
    '04-22': 'Kazimierza, Łukasza, Leonii',
    '04-23': 'Jerzego, Wojciecha, Adalberta',
    '04-24': 'Grzegorza, Horacego, Aleksego',
    '04-25': 'Marka, Jarosława, Wioletty',
    '04-26': 'Marzeny, Klaudiusza, Marii',
    '04-27': 'Zyty, Anastazego, Teofila',
    '04-28': 'Pawła, Walerii, Piotra',
    '04-29': 'Piotra, Rity, Hugona',
    '04-30': 'Mariana, Katarzyny, Jakuba',

    // --- Maj ---
    '05-01': 'Józefa, Jeremiasza, Lubomira', // Święto Pracy
    '05-02': 'Zygmunta, Anatola, Walentego',
    '05-03': 'Marii, Antoniny, Aleksandra', // Święto Konstytucji 3 Maja
    '05-04': 'Floriana, Moniki, Paulina', // Dzień Strażaka
    '05-05': 'Ireny, Waldemara, Grzegorza',
    '05-06': 'Jana, Judyty, Filipa',
    '05-07': 'Gizeli, Ludomira, Benedykta',
    '05-08': 'Stanisława, Lizy, Dezyderii',
    '05-09': 'Grzegorza, Karoliny, Bożydara',
    '05-10': 'Antoniego, Izydora, Wiktoryny',
    '05-11': 'Franciszka, Ignacego, Miry',
    '05-12': 'Pankracego, Dominika, Joanny',
    '05-13': 'Serwacego, Roberta, Glorii',
    '05-14': 'Bonifacego, Macieja, Dobiesława',
    '05-15': 'Zofii, Izydora, Jana',
    '05-16': 'Andrzeja, Szymona, Jędrzeja',
    '05-17': 'Paschalisa, Brunona, Sławomira',
    '05-18': 'Eryka, Feliksa, Jana',
    '05-19': 'Piotra, Iwa, Mikołaja',
    '05-20': 'Bernarda, Aleksandra, Bazylego',
    '05-21': 'Wiktora, Tymoteusza, Jana',
    '05-22': 'Rity, Julii, Heleny',
    '05-23': 'Iwony, Dezyderego, Emilii',
    '05-24': 'Joanny, Zuzanny, Jana',
    '05-25': 'Grzegorza, Urbana, Magdaleny',
    '05-26': 'Filipa, Pauliny, Eweliny', // Dzień Matki
    '05-27': 'Augustyna, Jana, Juliusza',
    '05-28': 'Jaromira, Justa, Wilhelma',
    '05-29': 'Magdaleny, Teodozji, Maksymina',
    '05-30': 'Feliksa, Joanny, Ferdynanda',
    '05-31': 'Anieli, Kamili, Petroneli',

    // --- Czerwiec ---
    '06-01': 'Jakuba, Konrada, Justyna', // Dzień Dziecka
    '06-02': 'Marii, Erazma, Eugeniusza',
    '06-03': 'Leszka, Kłotyldy, Owidiusza',
    '06-04': 'Karola, Franciszka, Helgi',
    '06-05': 'Bonifacego, Waltera, Kiry',
    '06-06': 'Norberta, Laurentego, Pauliny',
    '06-07': 'Roberta, Wiesławy, Antoniego',
    '06-08': 'Medarda, Maksyma, Seweryna',
    '06-09': 'Pelagii, Felicjana, Anny',
    '06-10': 'Bogumiła, Małgorzaty, Diany',
    '06-11': 'Barnaby, Benedykta, Feliksa',
    '06-12': 'Jana, Onufrego, Mieczysławy',
    '06-13': 'Antoniego, Lucyny, Gerarda',
    '06-14': 'Bazylego, Elizy, Justyna',
    '06-15': 'Wita, Jolanty, Modesta',
    '06-16': 'Aliny, Justyny, Benona',
    '06-17': 'Laury, Alberta, Adolfa',
    '06-18': 'Marka, Elżbiety, Pauliny',
    '06-19': 'Gerwazego, Protazego, Romualda',
    '06-20': 'Bogny, Florentyny, Rafała',
    '06-21': 'Alicji, Alojzego, Rudolfa',
    '06-22': 'Pauliny, Tomasza, Jana',
    '06-23': 'Wandy, Zenona, Albiny', // Dzień Ojca
    '06-24': 'Jana, Danuty, Emilii',
    '06-25': 'Łucji, Wilhelma, Doroty',
    '06-26': 'Jana, Pawła, Tytusa',
    '06-27': 'Marii, Władysława, Cyryla',
    '06-28': 'Leona, Ireneusza, Flory',
    '06-29': 'Piotra, Pawła, Władysławy',
    '06-30': 'Emilii, Lucyny, Arnolda',

    // --- Lipiec ---
    '07-01': 'Haliny, Mariana, Bogusza',
    '07-02': 'Marii, Urbana, Jagody',
    '07-03': 'Jacka, Anatola, Tomasza',
    '07-04': 'Elżbiety, Eugeniusza, Malwiny',
    '07-05': 'Antoniego, Karoliny, Bartłomieja',
    '07-06': 'Dominiki, Łucji, Gotfryda',
    '07-07': 'Cyryla, Metodego, Rudolfa',
    '07-08': 'Edgara, Elżbiety, Eugeniusza',
    '07-09': 'Weroniki, Zenona, Sylwii',
    '07-10': 'Filipa, Amelii, Witalisa',
    '07-11': 'Benedykta, Olgi, Kaliny',
    '07-12': 'Jana, Brunona, Weroniki',
    '07-13': 'Małgorzaty, Henryka, Sary',
    '07-14': 'Kamila, Izabeli, Marceliny',
    '07-15': 'Henryka, Włodzimierza, Bonawentury',
    '07-16': 'Marii, Mariki, Benedykta',
    '07-17': 'Aleksego, Anety, Bogdana',
    '07-18': 'Kamila, Szymona, Emilii',
    '07-19': 'Wincentego, Wodzisława, Marcina',
    '07-20': 'Czesława, Małgorzaty, Hieronima',
    '07-21': 'Daniela, Wiktora, Andrzeja',
    '07-22': 'Marii Magdaleny, Bolesława, Mileny',
    '07-23': 'Brygidy, Apolinarego, Bogny',
    '07-24': 'Kingi, Krystyny, Jakuba',
    '07-25': 'Krzysztofa, Jakuba, Walentyny',
    '07-26': 'Anny, Joachima, Hanny',
    '07-27': 'Julii, Natalii, Rudolfa',
    '07-28': 'Wiktora, Innocentego, Ady',
    '07-29': 'Marty, Ludwika, Olafa',
    '07-30': 'Julity, Piotra, Ludomira',
    '07-31': 'Ignacego, Heleny, Ludomira',

    // --- Sierpień ---
    '08-01': 'Alfonsa, Justyna, Piotra',
    '08-02': 'Kariny, Gustawa, Euzebiusza',
    '08-03': 'Lidii, Augusta, Nikodema',
    '08-04': 'Dominika, Protazego, Jana',
    '08-05': 'Marii, Oswalda, Abel',
    '08-06': 'Sławy, Jakuba, Wincentego',
    '08-07': 'Klaudii, Donaty, Kajetana',
    '08-08': 'Emiliana, Dominika, Cypriana',
    '08-09': 'Romana, Ryszarda, Edyty',
    '08-10': 'Wawrzyńca, Bogdana, Borysa',
    '08-11': 'Klary, Zuzanny, Lecha',
    '08-12': 'Lecha, Hilarii, Juliana',
    '08-13': 'Hipolita, Poncjana, Diany',
    '08-14': 'Maksymiliana, Alfreda, Euzebiusza',
    '08-15': 'Marii, Napoleona, Stelii', // Wniebowzięcie NMP, Święto Wojska Polskiego
    '08-16': 'Rocha, Stefana, Joachima',
    '08-17': 'Jacka, Anity, Joanny',
    '08-18': 'Ilony, Heleny, Klary',
    '08-19': 'Bolesława, Juliana, Jana',
    '08-20': 'Bernarda, Samuela, Sabiny',
    '08-21': 'Franciszka, Joanny, Piusa',
    '08-22': 'Marii, Cezarego, Tymoteusza',
    '08-23': 'Filipa, Apolinarego, Róży',
    '08-24': 'Bartłomieja, Jerzego, Emilii',
    '08-25': 'Ludwika, Luizy, Józefa',
    '08-26': 'Marii, Zefiryny, Aleksandra',
    '08-27': 'Moniki, Cezarego, Józefa',
    '08-28': 'Augustyna, Patrycji, Erazma',
    '08-29': 'Jana, Sabiny, Racibora',
    '08-30': 'Róży, Feliksa, Szczęsnego',
    '08-31': 'Rajmunda, Bohdana, Pauliny',

    // --- Wrzesień ---
    '09-01': 'Idziego, Bronisława, Egidiusza',
    '09-02': 'Stefana, Wilhelma, Juliana',
    '09-03': 'Izabeli, Grzegorza, Szymona',
    '09-04': 'Rozalii, Róży, Idy',
    '09-05': 'Laury, Wawrzyńca, Justyna',
    '09-06': 'Beaty, Eugeniusza, Zachariasza',
    '09-07': 'Reginy, Marka, Melchiora',
    '09-08': 'Marii, Adrianny, Klementyny',
    '09-09': 'Piotra, Sergiusza, Aldony',
    '09-10': 'Mikołaja, Łukasza, Klemensa',
    '09-11': 'Jacka, Hiacynty, Dagny',
    '09-12': 'Marii, Gwidona, Radzimira',
    '09-13': 'Jana, Eugenii, Aureliusza',
    '09-14': 'Bernarda, Roksany, Cypriana',
    '09-15': 'Marii, Nikodema, Albina',
    '09-16': 'Kornela, Cypriana, Edyty',
    '09-17': 'Roberta, Hildegardy, Justyna',
    '09-18': 'Józefa, Stanisława, Ireny',
    '09-19': 'Konstancji, Januarii, Teodora',
    '09-20': 'Eustachego, Faustyny, Ewy',
    '09-21': 'Mateusza, Jonasza, Hipolita',
    '09-22': 'Tomasza, Maurycego, Joachima',
    '09-23': 'Tekli, Bogusława, Linusa',
    '09-24': 'Gerarda, Teodora, Marii',
    '09-25': 'Aurelii, Kleofasa, Władysława',
    '09-26': 'Cypriana, Justyny, Damiana',
    '09-27': 'Wincentego, Kosmy, Mirabeli',
    '09-28': 'Wacława, Marka, Leonarda',
    '09-29': 'Michała, Michaliny, Rafała',
    '09-30': 'Hieronima, Zofii, Honoriusza', // Dzień Chłopaka

    // --- Październik ---
    '10-01': 'Remigiusza, Teresy, Danuty',
    '10-02': 'Teofila, Sławy, Dionizego',
    '10-03': 'Gerarda, Teresy, Heliodora',
    '10-04': 'Franciszka, Rozalii, Edwina',
    '10-05': 'Placyda, Faustyny, Rajmunda',
    '10-06': 'Brunona, Artura, Fryderyki',
    '10-07': 'Marii, Marka, Justyny',
    '10-08': 'Pelagii, Brygidy, Walerii',
    '10-09': 'Dionizego, Arnolda, Ludwika',
    '10-10': 'Franciszka, Pauliny, Danieli',
    '10-11': 'Emila, Marii, Aldony',
    '10-12': 'Maksymiliana, Eustachego, Krystyny',
    '10-13': 'Edwarda, Teofila, Bernarda',
    '10-14': 'Bernarda, Damiana, Kaliksta', // Dzień Nauczyciela
    '10-15': 'Teresy, Jadwigi, Leonarda',
    '10-16': 'Gawła, Jadwigi, Florentyny',
    '10-17': 'Ignacego, Wiktora, Małgorzaty',
    '10-18': 'Łukasza, Juliana, Hanny',
    '10-19': 'Piotra, Pawła, Ziemowita',
    '10-20': 'Ireny, Jana, Witalisa',
    '10-21': 'Urszuli, Hilarego, Jakuba',
    '10-22': 'Filipa, Korduli, Lody',
    '10-23': 'Seweryna, Teodora, Jana',
    '10-24': 'Rafała, Marcina, Antoniego',
    '10-25': 'Darii, Ingi, Maurycego',
    '10-26': 'Lucjana, Ewy, Damiana',
    '10-27': 'Wincentego, Iwony, Sabiny',
    '10-28': 'Szymona, Judy, Tadeusza',
    '10-29': 'Wioletty, Euzebii, Zenobii',
    '10-30': 'Przemysława, Edmunda, Alfonsa',
    '10-31': 'Augusta, Lucjana, Urbana', // Halloween

    // --- Listopad ---
    '11-01': 'Wszystkich Świętych', // Specjalny wpis dla święta
    '11-02': 'Bohdany, Dzień Zaduszny', // Specjalny wpis dla święta
    '11-03': 'Sylwii, Huberta, Marcina',
    '11-04': 'Karola, Olgierda, Emeryka',
    '11-05': 'Elżbiety, Sławomira, Dominika',
    '11-06': 'Feliksa, Leonarda, Ziemowita',
    '11-07': 'Ernesta, Antoniego, Bogumiła',
    '11-08': 'Seweryna, Klaudiusza, Wiktora',
    '11-09': 'Teodora, Ursyna, Genowefy',
    '11-10': 'Leona, Ludomira, Natalii',
    '11-11': 'Marcina, Bartłomieja, Teodora', // Narodowe Święto Niepodległości
    '11-12': 'Renaty, Witolda, Konrada',
    '11-13': 'Stanisława, Mikołaja, Liwii',
    '11-14': 'Wawrzyńca, Emila, Rogera',
    '11-15': 'Alberta, Leopolda, Idalii',
    '11-16': 'Marka, Gertrudy, Edmunda',
    '11-17': 'Grzegorza, Salomei, Elżbiety',
    '11-18': 'Romana, Tomasza, Karoliny',
    '11-19': 'Elżbiety, Seweryna, Matyldy',
    '11-20': 'Feliksa, Anatola, Rafała',
    '11-21': 'Konrada, Janusza, Marii',
    '11-22': 'Cecylii, Marka, Wszemiły',
    '11-23': 'Klemensa, Felicyty, Adeli',
    '11-24': 'Flory, Emmy, Franciszka',
    '11-25': 'Katarzyny, Erazma, Tęgomira',
    '11-26': 'Konrada, Sylwestra, Leonarda',
    '11-27': 'Waleriana, Wirgiliusza, Maksymiliana',
    '11-28': 'Zdzisława, Jakuba, Stefana',
    '11-29': 'Błażeja, Saturnina, Maury',
    '11-30': 'Andrzeja, Maury, Konstantego', // Andrzejki

    // --- Grudzień ---
    '12-01': 'Natalii, Eligiusza, Edmunda',
    '12-02': 'Balbiny, Pauliny, Ksawerego',
    '12-03': 'Franciszka, Ksawerego, Kasjana',
    '12-04': 'Barbary, Krystiana, Hieronima', // Barbórka (Dzień Górnika)
    '12-05': 'Sabiny, Kryspiny, Gerarda',
    '12-06': 'Mikołaja, Angeliki, Emila', // Mikołajki
    '12-07': 'Ambrożego, Marcina, Teodora',
    '12-08': 'Marii, Światozara, Klemensa',
    '12-09': 'Wiesławy, Leokadii, Joanny',
    '12-10': 'Julii, Danieli, Grzegorza',
    '12-11': 'Damazego, Waldemara, Daniela',
    '12-12': 'Aleksandra, Dagmary, Adama',
    '12-13': 'Łucji, Otylii, Zorzy',
    '12-14': 'Alfreda, Izydora, Jana',
    '12-15': 'Celiny, Waleriana, Niny',
    '12-16': 'Euzebiusza, Albiny, Zdzisławy',
    '12-17': 'Łazarza, Floriana, Olimpii',
    '12-18': 'Gracjana, Bogusława, Laurentego',
    '12-19': 'Gabrieli, Dariusza, Eleonory',
    '12-20': 'Dominika, Bogumiły, Teofila',
    '12-21': 'Tomasza, Piotra, Honoraty',
    '12-22': 'Zenona, Honoraty, Beaty',
    '12-23': 'Wiktorii, Sławomiry, Jana',
    '12-24': 'Adama, Ewy, Eweliny', // Wigilia Bożego Narodzenia
    '12-25': 'Anastazji, Eugenii, Piotra', // Boże Narodzenie
    '12-26': 'Szczepana, Dionizego, Wróciwoja', // Drugi dzień świąt
    '12-27': 'Jana, Żanety, Fabioli',
    '12-28': 'Teofilii, Antoniusza, Cezarego',
    '12-29': 'Tomasza, Dawida, Dominika',
    '12-30': 'Eugeniusza, Katarzyny, Sabiny',
    '12-31': 'Sylwestra, Melanii, Mariusza' // Sylwester
};

// Aby umożliwić innym plikom (modułom) korzystanie z tej bazy danych,
// można ją wyeksportować (np. w środowisku Node.js lub przy użyciu modułów ES6).
// Przykład dla modułów ES6 (jeśli to plik .mjs lub w projekcie używającym transpilatora):
// export default IMIENINY_BAZA;

// Przykład dla CommonJS (standard w Node.js):
// module.exports = IMIENINY_BAZA;
