// KOMENTARZ (Dlaczego?):
// Poprawiamy trzy rzeczy:
// 1. Dodajemy brakujący znak "=" po nazwie zmiennej.
// 2. Zmieniamy nazwę z "SWIETA_NIETYPOWE_BAZA" na "swietaData",
//    ponieważ tej nazwy szuka funkcja getSwieta() w pliku index.html.
// 3. Usuwamy dodatkowy nawias "}" na samym końcu pliku, który powodował błąd.
const swietaData = {
    '01-01': 'Światowy Dzień Kaca, Dzień Domeny Publicznej',
    '01-02': 'Dzień Nauczyciela Na Prądzie',
    '01-03': 'Dzień Słomki Do Picia',
    '01-04': 'Dzień Spaghetti',
    '01-05': 'Dzień Bitej Śmietany',
    '01-06': 'Dzień Wtulania Się',
    '01-07': 'Dzień Dziwaka',
    '01-08': 'Dzień Sprzątania Biurka',
    '01-09': 'Dzień Ligi Ochrony Przyrody',
    '01-10': 'Dzień Obniżania Kosztów Energii',
    '01-11': 'Dzień Wegetarian',
    '01-12': 'Dzień Całowania Złotowłosych',
    '01-13': 'Dzień Gumowej Kaczuszki',
    '01-14': 'Dzień Ukrytej Miłości',
    '01-15': 'Dzień Wikipedii',
    '01-16': 'Dzień Pikantnych Potraw',
    '01-17': 'Dzień Pizzy (Włochy)',
    '01-18': 'Dzień Kubusia Puchatka',
    '01-19': 'Dzień Popcornu',
    '01-20': 'Dzień Pingwina',
    '01-21': 'Dzień Babci',
    '01-22': 'Dzień Dziadka',
    '01-23': 'Dzień Pisma Ręcznego',
    '01-24': 'Światowy Dzień Śmiechu',
    '01-25': 'Dzień Sekretarki i Asystentki',
    '01-26': 'Dzień Drugiej Połówki',
    '01-27': 'Dzień Pamięci Ofiar Holocaustu',
    '01-28': 'Międzynarodowy Dzień Mobilizacji Przeciwko Wojnie Nuklearnej',
    '01-29': 'Dzień Składanki i Łamigłówki',
    '01-30': 'Dzień Rogalika',
    '01-31': 'Międzynarodowy Dzień Przytulania',
    '02-01': 'Dzień Ubezpieczyciela',
    '02-02': 'Dzień Pozytywnego Myślenia',
    '02-03': 'Dzień Ciasta Marchewkowego',
    '02-04': 'Międzynarodowy Dzień Walki z Rakiem',
    '02-05': 'Dzień Nutelli',
    '02-06': 'Dzień Boba Marleya',
    '02-07': 'Dzień Najwyższej Izby Kontroli',
    '02-08': 'Dzień Bezpiecznego Internetu',
    '02-09': 'Międzynarodowy Dzień Pizzy',
    '02-10': 'Dzień Dyplomaty',
    '02-11': 'Ogólnoświatowy Dzień Chorego',
    '02-12': 'Dzień Darwina',
    '02-13': 'Światowy Dzień Radia',
    '02-14': 'Walentynki',
    '02-15': 'Dzień Singla',
    '02-16': 'Dzień Rzucania Palenia (Polska)',
    '02-17': 'Światowy Dzień Kota',
    '02-18': 'Dzień Baterii',
    '02-19': 'Dzień Nauki Polskiej',
    '02-20': 'Dzień Leniwych Ludzi',
    '02-21': 'Międzynarodowy Dzień Języka Ojczystego',
    '02-22': 'Dzień Myśli Braterskiej',
    '02-23': 'Międzynarodowy Dzień Pomocy Potrzebującym',
    '02-24': 'Dzień Niespodziewanego Całusa',
    '02-25': 'Dzień Masturbacji (Japonia)',
    '02-26': 'Dzień Dinozaura',
    '02-27': 'Dzień Niedźwiedzia Polarnego',
    '02-28': 'Dzień Chorób Rzadkich',
    '02-29': 'Dzień Roku Przestępnego',
    '03-01': 'Dzień Piegów',
    '03-02': 'Dzień Starej Książki',
    '03-03': 'Międzynarodowy Dzień Pisarzy',
    '03-04': 'Dzień Walki z Otyłością',
    '03-05': 'Dzień Teściowej',
    '03-06': 'Dzień Czystego Stołu',
    '03-07': 'Dzień Płatków Śniadaniowych',
    '03-08': 'Dzień Kobiet',
    '03-09': 'Dzień Lalki Barbie',
    '03-10': 'Dzień Mężczyzn',
    '03-11': 'Dzień Sołtysa',
    '03-12': 'Światowy Dzień Drzemki w Pracy',
    '03-13': 'Dzień Klejnotów',
    '03-14': 'Dzień Liczby Pi',
    '03-15': 'Dzień Piekarzy i Cukierników',
    '03-16': 'Dzień Pandy',
    '03-17': 'Dzień Świętego Patryka',
    '03-18': 'Dzień Snu',
    '03-19': 'Dzień Wędkarza',
    '03-20': 'Międzynarodowy Dzień Szczęścia',
    '03-21': 'Dzień Wagarowicza',
    '03-22': 'Światowy Dzień Wody',
    '03-23': 'Dzień Windy',
    '03-24': 'Narodowy Dzień Życia',
    '03-25': 'Dzień Czytania Tolkiena',
    '03-26': 'Dzień Dobrego Łotra (Dzień Janosika)',
    '03-27': 'Międzynarodowy Dzień Teatru',
    '03-28': 'Dzień Chwastów',
    '03-29': 'Dzień Metalowca',
    '03-30': 'Dzień Ziemi Palestyńskiej',
    '03-31': 'Dzień Budyniu',
    '04-01': 'Prima Aprilis',
    '04-02': 'Międzynarodowy Dzień Książki dla Dzieci',
    '04-03': 'Dzień Tęczy',
    '04-04': 'Dzień Marchewki',
    '04-05': 'Dzień Karmelu',
    '04-06': 'Dzień Sportu dla Rozwoju i Pokoju',
    '04-07': 'Dzień Pracownika Służby Zdrowia',
    '04-08': 'Dzień Miłośników Zoo',
    '04-09': 'Dzień Mówienia o Pieniądzach',
    '04-10': 'Dzień Rodzeństwa',
    '04-11': 'Dzień Radia',
    '04-12': 'Dzień Czystych Okien',
    '04-13': 'Dzień Pamięci Ofiar Zbrodni Katyńskiej',
    '04-14': 'Dzień Delfina',
    '04-15': 'Światowy Dzień Sztuki',
    '04-16': 'Dzień Włókniarza',
    '04-17': 'Światowy Dzień Chorych na Hemofilię',
    '04-18': 'Międzynarodowy Dzień Ochrony Zabytków',
    '04-19': 'Dzień Czosnku',
    '04-20': 'Międzynarodowy Dzień Wolnej Prasy',
    '04-21': 'Dzień Herbaty (UK)',
    '04-22': 'Międzynarodowy Dzień Ziemi',
    '04-23': 'Światowy Dzień Książki i Praw Autorskich',
    '04-24': 'Dzień Przeciwko Wiwisekcji',
    '04-25': 'Dzień Pingwina',
    '04-26': 'Dzień Własności Intelektualnej',
    '04-27': 'Światowy Dzień Grafika',
    '04-28': 'Dzień Sera Feta',
    '04-29': 'Międzynarodowy Dzień Tańca',
    '04-30': 'Międzynarodowy Dzień Jazzu',
    '05-01': 'Święto Pracy',
    '05-02': 'Dzień Flagi Rzeczypospolitej Polskiej',
    '05-03': 'Święto Konstytucji 3 Maja',
    '05-04': 'Dzień Gwiezdnych Wojen (May the 4th)',
    '05-05': 'Dzień Bez Makijażu',
    '05-06': 'Międzynarodowy Dzień Bez Diety',
    '05-07': 'Dzień Śmiechu',
    '05-08': 'Dzień Bibliotekarza i Bibliotek',
    '05-09': 'Dzień Unii Europejskiej',
    '05-10': 'Dzień Pracownika Gospodarki Komunalnej',
    '05-11': 'Dzień bez Śmiecenia',
    '05-12': 'Międzynarodowy Dzień Pielęgniarek',
    '05-13': 'Dzień Hummusu',
    '05-14': 'Dzień Farmaceuty',
    '05-15': 'Międzynarodowy Dzień Rodzin',
    '05-16': 'Dzień Płynów do Mycia Naczyń',
    '05-17': 'Międzynarodowy Dzień Przeciw Homofobii',
    '05-18': 'Międzynarodowy Dzień Muzeów',
    '05-19': 'Dzień Dobrych Uczynków',
    '05-20': 'Światowy Dzień Pszczół',
    '05-21': 'Dzień Kosmosu',
    '05-22': 'Dzień Praw Zwierząt',
    '05-23': 'Dzień Żółwia',
    '05-24': 'Dzień Braci',
    '05-25': 'Dzień Ręcznika (Dzień Pamięci Douglasa Adamsa)',
    '05-26': 'Dzień Matki',
    '05-27': 'Dzień Samorządu Terytorialnego',
    '05-28': 'Dzień Hamburgera',
    '05-29': 'Dzień Działacza Kultury',
    '05-30': 'Dzień Bez Majtek',
    '05-31': 'Dzień Bez Papierosa',
    '06-01': 'Dzień Dziecka',
    '06-02': 'Dzień Sąsiada',
    '06-03': 'Dzień Roweru',
    '06-04': 'Dzień Wolności i Praw Obywatelskich',
    '06-05': 'Dzień Ochrony Środowiska',
    '06-06': 'Dzień Pocałunku',
    '06-07': 'Dzień Chemika',
    '06-08': 'Dzień Oceanów',
    '06-09': 'Dzień Przyjaciela',
    '06-10': 'Dzień Straży Granicznej',
    '06-11': 'Dzień Robienia na Drutach w Miejscach Publicznych',
    '06-12': 'Światowy Dzień Sprzeciwu Wobec Pracy Dzieci',
    '06-13': 'Dzień Pisarza',
    '06-14': 'Światowy Dzień Krwiodawcy',
    '06-15': 'Dzień Wiatru',
    '06-16': 'Dzień Ojca (w niektórych krajach)',
    '06-17': 'Dzień Walki z Pustynnieniem i Suszą',
    '06-18': 'Dzień Sushi',
    '06-19': 'Dzień Leniwego Wstawania',
    '06-20': 'Światowy Dzień Uchodźcy',
    '06-21': 'Dzień Deskorolki',
    '06-22': 'Dzień Bez Przekleństw',
    '06-23': 'Dzień Ojca',
    '06-24': 'Dzień Przytulania',
    '06-25': 'Dzień Marynarza',
    '06-26': 'Międzynarodowy Dzień Walki z Narkotykami',
    '06-27': 'Dzień Walki z Cukrzycą',
    '06-28': 'Narodowy Dzień Pamięci Poznańskiego Czerwca 1956',
    '06-29': 'Dzień Ratownika WOPR',
    '06-30': 'Dzień Motyla',
    '07-01': 'Dzień Psa',
    '07-02': 'Dzień Dziennikarza Sportowego',
    '07-03': 'Dzień Bez Foliówek',
    '07-04': 'Dzień Hot-Doga',
    '07-05': 'Dzień Łapania Za Biust (nieoficjalne)',
    '07-06': 'Światowy Dzień Pocałunku',
    '07-07': 'Dzień Czekolady',
    '07-08': 'Dzień Gry Wideo',
    '07-09': 'Dzień Chodzenia do Pracy Inną Drogą',
    '07-10': 'Dzień Nikoli Tesli',
    '07-11': 'Narodowy Dzień Pamięci Ofiar Ludobójstwa na Wołyniu',
    '07-12': 'Dzień Frytek',
    '07-13': 'Dzień Chodzenia Bez Stanika',
    '07-14': 'Dzień Zdobycia Bastylii',
    '07-15': 'Dzień Bez Telefonu Komórkowego',
    '07-16': 'Dzień Węża',
    '07-17': 'Światowy Dzień Emoji',
    '07-18': 'Dzień Nelsona Mandeli',
    '07-19': 'Dzień Czerwonego Kapturka',
    '07-20': 'Międzynarodowy Dzień Szachów',
    '07-21': 'Dzień Lodów',
    '07-22': 'Dzień Hamaka',
    '07-23': 'Dzień Włóczykija',
    '07-24': 'Dzień Policjanta',
    '07-25': 'Dzień Bezpiecznego Kierowcy',
    '07-26': 'Dzień Administratora',
    '07-27': 'Dzień Samotnych',
    '07-28': 'Światowy Dzień Wirusowego Zapalenia Wątroby',
    '07-29': 'Dzień Tygrysa',
    '07-30': 'Międzynarodowy Dzień Przyjaźni',
    '07-31': 'Dzień Urodzin Harry\'ego Pottera',
    '08-01': 'Narodowy Dzień Pamięci Powstania Warszawskiego',
    '08-02': 'Dzień Kolorowanek',
    '08-03': 'Dzień Arbuza',
    '08-04': 'Międzynarodowy Dzień Piwa i Piwowara',
    '08-05': 'Dzień Musztardy',
    '08-06': 'Dzień Musztardy',
    '08-07': 'Dzień Pracownika Ochrony',
    '08-08': 'Międzynarodowy Dzień Kota',
    '08-09': 'Dzień Miłośników Książek',
    '08-10': 'Dzień Lwa',
    '08-11': 'Dzień Konserwatora Zabytków',
    '08-12': 'Międzynarodowy Dzień Młodzieży',
    '08-13': 'Międzynarodowy Dzień Osób Leworęcznych',
    '08-14': 'Dzień Energetyka',
    '08-15': 'Święto Wojska Polskiego',
    '08-16': 'Dzień Rollerco rollercoastera',
    '08-17': 'Dzień Pozytywnie Zakręconych',
    '08-18': 'Dzień Sernika',
    '08-19': 'Światowy Dzień Fotografii',
    '08-20': 'Dzień Komara',
    '08-21': 'Dzień Bez Makijażu',
    '08-22': 'Dzień Pracownika Ochrony',
    '08-23': 'Dzień Internauty',
    '08-24': 'Dzień Ukrainy',
    '08-25': 'Dzień Całowania Się W Usta',
    '08-26': 'Dzień Psa',
    '08-27': 'Dzień Tira',
    '08-28': 'Dzień Publicznego Czytania Komiksów',
    '08-29': 'Międzynarodowy Dzień Przeciw Próbom Jądrowym',
    '08-30': 'Dzień Taksówkarza',
    '08-31': 'Dzień Blogów',
    '09-01': 'Dzień Weterana',
    '09-02': 'Dzień Dużego Dziecka',
    '09-03': 'Dzień Wieżowców',
    '09-04': 'Dzień Orzechów Makadamia',
    '09-05': 'Międzynarodowy Dzień Dobroczynności',
    '09-06': 'Dzień Walki z Prokrastynacją',
    '09-07': 'Dzień Czystego Powietrza',
    '09-08': 'Dzień Marzyciela',
    '09-09': 'Międzynarodowy Dzień Urody',
    '09-10': 'Światowy Dzień Zapobiegania Samobójstwom',
    '09-11': 'Dzień Czołgisty',
    '09-12': 'Dzień Programisty (jeśli rok przestępny)',
    '09-13': 'Dzień Programisty (jeśli rok nieprzestępny)',
    '09-14': 'Dzień Walki z Wypaleniem Zawodowym',
    '09-15': 'Międzynarodowy Dzień Demokracji',
    '09-16': 'Międzynarodowy Dzień Ochrony Warstwy Ozonowej',
    '09-17': 'Dzień Sybiraka',
    '09-18': 'Międzynarodowy Dzień Geologa',
    '09-19': 'Międzynarodowy Dzień Mówienia Jak Pirat',
    '09-20': 'Dzień Przedszkolaka',
    '09-21': 'Międzynarodowy Dzień Pokoju',
    '09-22': 'Dzień Bez Samochodu',
    '09-23': 'Pierwszy Dzień Jesieni',
    '09-24': 'Dzień Grzybów',
    '09-25': 'Dzień Budowlańca',
    '09-26': 'Europejski Dzień Języków',
    '09-27': 'Światowy Dzień Turystyki',
    '09-28': 'Światowy Dzień Wścieklizny',
    '09-29': 'Dzień Kawy',
    '09-30': 'Dzień Chłopaka',
    '10-01': 'Międzynarodowy Dzień Osób Starszych',
    '10-02': 'Międzynarodowy Dzień Bez Przemocy',
    '10-03': 'Światowy Dzień Uśmiechu',
    '10-04': 'Światowy Dzień Zwierząt',
    '10-05': 'Dzień Nauczyciela (Światowy)',
    '10-06': 'Dzień Borsuka',
    '10-07': 'Dzień Wdzięczności dla Chłopaków',
    '10-08': 'Dzień Ośmiornicy',
    '10-09': 'Światowy Dzień Poczty i Znaczka Pocztowego',
    '10-10': 'Światowy Dzień Zdrowia Psychicznego',
    '10-11': 'Dzień Dziewczyn',
    '10-12': 'Dzień Bezpiecznego Komputera',
    '10-13': 'Dzień Bez Stanika',
    '10-14': 'Dzień Nauczyciela (Polska)',
    '10-15': 'Światowy Dzień Mycia Rąk',
    '10-16': 'Światowy Dzień Żywności',
    '10-17': 'Międzynarodowy Dzień Walki z Ubóstwem',
    '10-18': 'Dzień Poczty Polskiej (Dzień Listonosza)',
    '10-19': 'Dzień Ratownika Medycznego',
    '10-20': 'Dzień Leniwca',
    '10-21': 'Dzień Bez Skarpetek',
    '10-22': 'Dzień Kapsla',
    '10-23': 'Dzień Mola Książkowego',
    '10-24': 'Dzień Walki z Otyłością',
    '10-25': 'Dzień Kundelka',
    '10-26': 'Dzień Pamięci o Ofiarach Wypadków Drogowych',
    '10-27': 'Dzień Praw Człowieka',
    '10-28': 'Dzień Odpoczynku dla Zszarganych Nerwów',
    '10-29': 'Dzień Internetu',
    '10-30': 'Dzień Spódnicy',
    '10-31': 'Halloween',
    '11-01': 'Wszystkich Świętych',
    '11-02': 'Dzień Zaduszny',
    '11-03': 'Dzień Myśliwego (Św. Huberta)',
    '11-04': 'Dzień Taniego Wina',
    '11-05': 'Międzynarodowy Dzień Postaci z Bajek',
    '11-06': 'Dzień Saksofonu',
    '11-07': 'Dzień Kotleta Schabowego',
    '11-08': 'Europejski Dzień Zdrowego Jedzenia i Gotowania',
    '11-09': 'Dzień Gry Wstępnej',
    '11-10': 'Dzień Jeża',
    '11-11': 'Narodowe Święto Niepodległości',
    '11-12': 'Dzień Bicia Rekordów',
    '11-13': 'Międzynarodowy Dzień Niewidomych',
    '11-14': 'Dzień Cukrzycy',
    '11-15': 'Dzień Uwięzionego Pisarza',
    '11-16': 'Międzynarodowy Dzień Tolerancji',
    '11-17': 'Dzień Studenta',
    '11-18': 'Dzień Myszki Miki',
    '11-19': 'Międzynarodowy Dzień Mężczyzn',
    '11-20': 'Dzień Praw Dziecka',
    '11-21': 'Dzień Życzliwości i Pozdrowień',
    '11-22': 'Dzień Kredki',
    '11-23': 'Dzień Fibonacciego',
    '11-24': 'Dzień Buraka',
    '11-25': 'Dzień Pluszowego Misia',
    '11-26': 'Dzień Ciasta',
    '11-27': 'Dzień Bez Kupowania',
    '11-28': 'Dzień Pocałunku',
    '11-29': 'Dzień Podchorążego',
    '11-30': 'Andrzejki',
    '12-01': 'Światowy Dzień AIDS',
    '12-02': 'Międzynarodowy Dzień Upamiętniający Zniesienie Niewolnictwa',
    '12-03': 'Międzynarodowy Dzień Osób Niepełnosprawnych',
    '12-04': 'Dzień Górnika (Barbórka)',
    '12-05': 'Dzień Wolontariusza',
    '12-06': 'Mikołajki',
    '12-07': 'Międzynarodowy Dzień Lotnictwa Cywilnego',
    '12-08': 'Dzień Kupca',
    '12-09': 'Międzynarodowy Dzień Przeciwdziałania Korupcji',
    '12-10': 'Dzień Praw Człowieka',
    '12-11': 'Międzynarodowy Dzień Terenów Górskich',
    '12-12': 'Dzień Guzika',
    '12-13': 'Dzień Księgarza',
    '12-14': 'Dzień Małpy',
    '12-15': 'Dzień Herbaty',
    '12-16': 'Dzień Pokrywania Wszystkiego Czekoladą',
    '12-17': 'Dzień Bez Przekleństw',
    '12-18': 'Międzynarodowy Dzień Migrantów',
    '12-19': 'Dzień Wiecznie Zielonych Roślin',
    '12-20': 'Dzień Gier Planszowych',
    '12-21': 'Dzień Orgazmu (Globalny)',
    '12-22': 'Pierwszy Dzień Zimy',
    '12-23': 'Dzień Ryby',
    '12-24': 'Wigilia',
    '12-25': 'Boże Narodzenie',
    '12-26': 'Boże Narodzenie (II dzień)',
    '12-27': 'Dzień Odpoczynku',
    '12-28': 'Dzień Całowania Płatków Śniegu',
    '12-29': 'Dzień Kostki do Gry',
    '12-30': 'Dzień Serka Wiejskiego',
    '12-31': 'Sylwestra'
};
